backend:
  name: git-gateway
  branch: main
  local_backend: true


media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
